version: '3.9'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    secrets:
      - cloudflare_tunnel_token
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/cloudflare_tunnel_token
      - NO_COLOR=true
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - public_edge_net

networks:
  public_edge_net:
    external: true

secrets:
  cloudflare_tunnel_token:
    external: true
